package com.example.emran2020;

import androidx.appcompat.app.AppCompatActivity;

import android.app.AlertDialog;
import android.os.Bundle;
import android.view.View;

public class Main28Activity<ex1> extends AppCompatActivity {



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate ( savedInstanceState );
        setContentView ( R.layout.activity_main28 );
    }

    public String ex1 = "A treadmill is a device generally for walking, running or climbing while staying in the same place. " +
           "treadmills were used as punishment devices for people sentenced to hard labour in prisons.";



    public  String ex2 = "rowing machine is a machine used to simulate the action of watercraft rowing for the purpose of exercise" +
            " or training for rowing. Indoor rowing has become established as a sport in its own right.\n" +
            "An extremely efficient method of exercise, rowing uses 86% of muscles when done with correct form." +
            " Its health benefits are often contrasted with those of spinning, since both are dually categorized as static and dynamic exercises\n";


    public String ex3="Exercise bikes are used for exercise, to increase general fitness, for weight loss, and for training for cycle events." +
            " The exercise bike has long been used for physical therapy because of the low-impact, safe, and effective cardiovascular exercise " +
            "it provides. The low-impact movement involved in operating an exercise bike does not put much stress on joints and" +
            " does not involve sporadic motions that some other fitness equipment may require.[citation needed] " +
            "However, as with typical biking, extended use of a stationary bike has been linked to decreased sexual function.";


    public String ex4 ="Weight training is a common type of strength training for developing the strength and size of skeletal muscles." +
            " It utilizes the force of gravity in the form of weighted bars, dumbbells, or weight stacks in order to oppose" +
            " the force generated by muscle through concentric or eccentric contraction. " +
            "Weight training uses a variety of specialized equipment to target specific muscle groups and types of movement.";



    public String ex5="A resistance band is an elastic band used for strength training." +
            " They are also commonly used in physical therapy, specifically by convalescents of muscular injuries," +
            " including cardiac rehab patients to allow slow rebuilding of strength.";



    public String ex6="An elliptical trainer or cross-trainer is a stationary exercise machine used to stair climb, walk," +
            " or run without causing excessive pressure to the joints, hence decreasing the risk of impact injuries." +
            " For this reason, people with some injuries can use an elliptical to stay fit, as the low impact affects them little. " +
            "Elliptical trainers offer a non-impact cardiovascular workout that can vary from light to high intensity based on the speed" +
            " of the exercise and the resistance preference set by the user.";

    public void exercise1(View view) {
        AlertDialog.Builder builder= new AlertDialog.Builder ( Main28Activity.this );
        builder.setTitle ( "Treadmill Exercise:" );
        builder.setMessage ( ex1);
        builder.setIcon ( R.drawable.png1);
        builder.setPositiveButton ( "Thanks", null);

        builder.create ();
        builder.show ();

    }

    public void exercise2(View view) {
        AlertDialog.Builder builder= new AlertDialog.Builder ( Main28Activity.this );
        builder.setTitle ( "Rowing Exercise:" );
        builder.setMessage ( ex2);
        builder.setIcon ( R.drawable.png2);
        builder.setPositiveButton ( "Thanks", null);

        builder.create ();
        builder.show ();




    }


    public void exercise3(View view) {
        AlertDialog.Builder builder= new AlertDialog.Builder ( Main28Activity.this );
        builder.setTitle ( "Bike Exercise:" );
        builder.setMessage ( ex3);
        builder.setIcon ( R.drawable.png3);
        builder.setPositiveButton ( "Thanks", null);

        builder.create ();
        builder.show ();




    }
    public void exercise4(View view) {
        AlertDialog.Builder builder= new AlertDialog.Builder ( Main28Activity.this );
        builder.setTitle ( "Free Weights Exercise:" );
        builder.setMessage ( ex4);
        builder.setIcon ( R.drawable.png4);
        builder.setPositiveButton ( "Thanks", null);

        builder.create ();
        builder.show ();




    }
    public void exercise5(View view) {
        AlertDialog.Builder builder= new AlertDialog.Builder ( Main28Activity.this );
        builder.setTitle ( "Rubber Bands Exercise:" );
        builder.setMessage ( ex5);
        builder.setIcon ( R.drawable.png5);
        builder.setPositiveButton ( "Thanks", null);

        builder.create ();
        builder.show ();




    }
    public void exercise6(View view) {
        AlertDialog.Builder builder= new AlertDialog.Builder ( Main28Activity.this );
        builder.setTitle ( "Elliptic Exercise:" );
        builder.setMessage (ex6);
        builder.setIcon ( R.drawable.png6);
        builder.setPositiveButton ( "Thanks", null);

        builder.create ();
        builder.show ();




    }

}
